### ISSUE TITLE
render svg's

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore-component-library#13]
# story
the Image component only currently accepts jpg, png and other image formats. we want to be able to use svg's in our app too. whether that means the Image component accepts svg files/components or we create a new component for svg's

# acceptance criteria

- [x] we are able to render svg image files
- [ ] we are able to render svg components

**Comment by summer-cook** [comment]
closing this one- we realized that since the image component can already accept an svg file, we were originally trying to have it accept an svg component. but in the case that there IS an svg component, the user can just render the SVG component itself
