### ISSUE TITLE
update Link prop types

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore-component-library#165]
ref: https://github.com/scientist-softserv/webstore-component-library/pull/162#discussion_r1113394129

# story
in the pr above, the Link component was changed to no longer require a label. that means however that both the "icon" and "label" values are not required. for a Link, this should not be. it should be required that there is some type of value that the user clicks in order to be directed somewhere.

# acceptance criteria
- [ ] the Link component requires a minimum of an icon or label
- [ ] existing components using the Link component are updated as/if necessary

**Comment by summer-cook** [comment]
Maybe something like this: https://stackoverflow.com/questions/54751283/react-proptypes-at-least-one-of-these-props-must-be-provided

**Comment by alishaevn** [comment]
> Maybe something like this: https://stackoverflow.com/questions/54751283/react-proptypes-at-least-one-of-these-props-must-be-provided

^ unsure. in my experience, the `oneOf` function is used to make sure that the value of a specific key is one of the listed values, like [this](https://github.com/scientist-softserv/webstore-component-library/blob/main/src/components/SocialIcon/SocialIcon.jsx#L32).

I was thinking of instead of something like the below. but it's just my first thought. we may explore other solutions.

``` js
prop: PropTypes.exact({
  label: PropTypes.string,
  icon: Proptypes.string,
}).isRequired 
```
