### ISSUE TITLE
fix nil files issue

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore-component-library#166]
# summary
- error introduced by adding files PR
- requests without any files will hit this error

# screenshot

![Image](https://user-images.githubusercontent.com/73361970/220456617-381bc471-296f-4ed8-bb2f-58733b8c8f51.png)

**Comment by alishaevn** [comment]
a discussion was had on #167 and the outcome was that this error is better handled from the webstore.

webstore pr: https://github.com/scientist-softserv/webstore/pull/225
