### ISSUE TITLE
request title duplication

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore-component-library#179]
# story
for some reason, the identifier is being duplicated each time the sow is accepted. in the example below i accepted the sow many times, and this is what happened.

we need to test whether this is still an issue, and if so, fix it. 

# Screenshots

![Image](https://user-images.githubusercontent.com/73361970/223530343-b790f689-0d07-4633-8b9a-e7d8ab18ad49.png)

# acceptance criteria
- [ ] If I accept an SOW more than one time, the identifier does not get duplicated in the title.

**Comment by summer-cook** [comment]
something similar happens in the marketplace too so might not be our fault:


![Image](https://user-images.githubusercontent.com/73361970/223721026-90ed8c1d-950a-489d-8130-db6ca49f2f9d.png)

**Comment by summer-cook** [comment]
happening in the marketplace too potentially?

![Image](https://user-images.githubusercontent.com/73361970/223721805-263d39c0-3625-4d3c-a3bf-0b8ec855eaf2.png)

**Comment by alishaevn** [comment]
removing from the project board since this is not something we can currently duplicate.

**Comment by summer-cook** [comment]
cannot replicate this again- closing
