### ISSUE TITLE
update the Footer component

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore-component-library#194]
# acceptance criteria
- [x] linkedIn is added to the `iconsList` object in SocialIcon.jsx
- [x] the 3 section columns in the middle are made smaller
  - the title is size 13
  - the links are size 13
- [x] a link titled "Legal Notices" is placed on the left hand side underneath the copyright info (font-size: 13px)
- [x] copyright info gets reduced to an `h6`
- [ ] the margin top/bottom of the footer is reduced

# story
phenovista has requested a linkedIn icon be added to their footer's list of social icons. while we're updating that component, we'd like to add a few more changes as well.

# screenshots
this was done using the inspect tool, so use it as a reference only
<img width="572" alt="image" src="https://github.com/scientist-softserv/webstore-component-library/assets/29032869/37b2b037-b2b8-4d96-b3a1-f52a00586efd">

**Comment by summer-cook** [comment]
the work for this is done, but it is not yet deployed. should we make a deploy to staging column specifically for webstore stuff? @alishaevn

**Comment by alishaevn** [comment]
this was released in https://github.com/scientist-softserv/webstore-component-library/releases/tag/0.1.18
