### ISSUE TITLE
RefineRequests component

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore-component-library#2]
## summary
create a new compound per the specs below

## acceptance criteria
- [ ] 

## demo

![Image](https://user-images.githubusercontent.com/29032869/201748869-4dd4fc9f-05ea-4798-80ea-ce06171a8aec.png)

**Comment by alishaevn** [comment]
we decided today that this component isn't necessary for the mvp.
thread: https://assaydepot.slack.com/archives/C03FZDALABG/p1669050498871029
