### ISSUE TITLE
initial error component

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore-component-library#25]
# story
create a component that shows if an error status is returned from the api

# acceptance criteria
- [ ] handling errors in a meaningful way

# implementation ideas
- we could use the bootstrap [alert component](https://react-bootstrap.netlify.app/components/alerts/) with the "danger" variant
- have different versions that show for dev and prod use cases
  - dev: we may want the stack trace, status, code, etc.
  - prod: change text depending on the error status? e.g. a 500 error lets them know something went wrong internally and we're looking into it, while a 400 asks them to try again?

# demo
<details>
<summary>example of an error from the useSWR hook</summary>

![Image](https://user-images.githubusercontent.com/29032869/201160132-5aac1f7d-938d-4953-95fb-0cc4fd2ec8c6.png)
</details>

**Comment by summer-cook** [comment]
related webstore pr: https://github.com/scientist-softserv/webstore/pull/136

**Comment by alishaevn** [comment]
related: https://github.com/scientist-softserv/webstore-component-library/issues/136
