### ISSUE TITLE
Messages component

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore-component-library#5]
## summary
a user and supplier ought to be able to send messages back and forth to each other
- either person can start the conversation per [this thread](https://assaydepot.slack.com/archives/C03FZDALABG/p1669656598764459)
- the component is just one message
- there will be a `messages` array on the webtore that's mapped over to render as many messages as needed
- the initials will be for the user (first and last) and the supplier (first initial of the first two words of their name. if one name, then one letter)
- one color behind the user's name, another behind the supplier's name
- display the full message, no matter the length

## demo

![Image](https://user-images.githubusercontent.com/29032869/204395837-2b6b9da0-aabc-46b5-aa6d-14f9e25585dc.png)

**Comment by alishaevn** [comment]
message related files in the rx app
- https://github.com/assaydepot/rx/blob/cc63fa3b000f6efaf9d0a6558904cc0587c36328/app/views/quote_groups/_dashboard_beta_note.html.haml
- https://github.com/assaydepot/rx/blob/cc63fa3b000f6efaf9d0a6558904cc0587c36328/app/views/quote_groups/_dashboard_beta_note_body.html.haml
