### ISSUE TITLE
Documents component

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore-component-library#6]
## summary
- create/use a block element that shows the sow, estimate, proposal etc returned by the supplier
- clicking on that element should show details about the type of document that was selected

api references: https://github.com/scientist-softserv/webstore/issues/21#issuecomment-1289165248

## wireframe
![Image](https://user-images.githubusercontent.com/29032869/201754844-acc07365-7ed1-415d-aac4-f71f59c43e60.png)

# example from the marketplace

https://user-images.githubusercontent.com/29032869/203605641-38a1489a-1ea6-4143-9fbf-2d5bce1e8299.mp4

**Comment by alishaevn** [comment]
we could use the canvas bs5 component for when one of the documents is clicked on. that'll mimic what happens in the marketplace.

**Comment by summer-cook** [comment]
summer & alisha 
brainstorming: 



![Image](https://user-images.githubusercontent.com/73361970/203633607-c39d43b1-8472-4dfe-85dd-4462f76a9495.png)

**Comment by summer-cook** [comment]
![Image](https://user-images.githubusercontent.com/73361970/204317678-b0e19772-650f-409c-b5ee-f7a4f534c4cf.png)

**Comment by summer-cook** [comment]
![Image](https://user-images.githubusercontent.com/73361970/204317907-0e4b0ba9-0481-4e11-9171-1763f2dc3c24.png)

**Comment by summer-cook** [comment]
Next Actions dropdown:
- submit for approval

- will not do anything right now
(all we need for now)
