### ISSUE TITLE
Action component

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore-component-library#63]
# story
create the "action" component to be primarily used on an individual request page. we only have 1 action for the mvp, but more will be added later.

# acceptance criteria
- [ ] representative icon
- [ ] call to action
- [ ] action that happens when the button is pressed

# demo

![Image](https://user-images.githubusercontent.com/29032869/204380396-564ca936-b3d0-413b-9e20-c2fbcef9539c.png)

**Comment by alishaevn** [comment]
the "send message" doesn't currently exist so we won't actually be performing that action yet.
the status for the api update can be tracked at: https://github.com/assaydepot/scientist_api_v2/issues/167

**Comment by summer-cook** [comment]
@alishaevn is there an icon library added to this project?

**Comment by alishaevn** [comment]
@summer-cook no, there currently isn't one. on the status bar ticket I suggested that we may need to add font awesome, but I'll have to look into how to do that with storybook.

**Comment by alishaevn** [comment]
reopening because we need to include attachments when sending a message.
